### ISSUE TITLE
httpToStatsd implementation

### ISSUE THREAD

**Issue by pihomeserver** [M6Web/HttpToStatsd#11]
Hello
I ask myself about the best way to implement httpToStatsd in a project.
In my case my architecture is i think classical : 
- A backend server with Statsd and a database (InfluxDb here)
- A frontend with a node app (splitted in two parts client and server) and Nginx as a proxy to not expose the app.

Then i want to allow external applications/systems/whatever to send metrics to statsd. Then i guess that the best place to install httpToStatsd is to put it on the frontend server using Nginx as a proxy also.

Can you please confirm that i'm on the good way ?

**Comment by omansour** [comment]
I think so. 

and use only httpToStatsd to the client side. you can use directly node-statsd server side.

**Comment by pihomeserver** [comment]
Merci
