### ISSUE TITLE
token sent and token build should be compared using upperCase

### ISSUE THREAD

**Issue by pihomeserver** [M6Web/HttpToStatsd#9]
I got errors due to token comparisons line 23 in 'lib/security/securitytokenchecker.js'

IMHO both values should be compared once set to upperCase to avoid errors due to char value

**Comment by omansour** [comment]
yeah why not. 

can you propose a pull request to do that ?

**Comment by pihomeserver** [comment]
Olivier, 
I made one but please take care of it because it's the first one i ever done so not sure at all that i'm not doing something wrong

**Comment by omansour** [comment]
yep. maybe theres a problem on your token calculation client side. We use this software on production since quite a long time.

**Comment by pihomeserver** [comment]
In my tests i calculate it online not with node. It’s to avoid errors if the calculation is not made like the one included in the package
